export enum EPaymentSettingType {
  PAYPAL = 'paypal',
  STRIPE = 'stripe',
}

export enum EAllEventsReference {
  BATCH_CREATED = 'batch.created',
  BATCH_UPDATED = 'batch.updated',
  BATCH_CANCELED = 'batch.canceled',
  BATCH_PRE_PROCESSED = 'batch.pre_processed',
  BATCH_CONFIRMED = 'batch.confirmed',
  BATCH_PROCESSING = 'batch.processing',
  BATCH_COMPLETED = 'batch.completed',
  BATCH_FAILED = 'batch.failed',
  CART_CUSTOMER_UPDATED = 'cart.customer_updated',
  CART_CREATED = 'cart.created',
  CART_UPDATED = 'cart.updated',
  CLAIM_CREATED = 'claim.created',
  CLAIM_UPDATED = 'claim.updated',
  CLAIM_CANCELED = 'claim.canceled',
  CLAIM_FULFILLMENT_CREATED = 'claim.fulfillment_created',
  CLAIM_SHIPMENT_CREATED = 'claim.shipment_created',
  CLAIM_REFUND_PROCESSED = 'claim.refund_processed',
  CLAIM_ITEM_CREATED = 'claim_item.created',
  CLAIM_ITEM_UPDATED = 'claim_item.updated',
  CLAIM_ITEM_CANCELED = 'claim_item.canceled',
  CURRENCY_UPDATED = 'currency.updated',
  CUSTOMER_CREATED = 'customer.created',
  CUSTOMER_UPDATED = 'customer.updated',
  CUSTOMER_PASSWORD_RESET = 'customer.password_reset',
  DRAFT_ORDER_CREATED = 'draft_order.created',
  DRAFT_ORDER_UPDATED = 'draft_order.updated',
  GIFT_CARD_CREATED = 'gift_card.created',
  INVENTORY_ITEM_CREATED = 'inventory-item.created',
  INVENTORY_ITEM_UPDATED = 'inventory-item.updated',
  INVENTORY_ITEM_DELETED = 'inventory-item.deleted',
  INVENTORY_LEVEL_CREATED = 'inventory-level.created',
  INVENTORY_LEVEL_UPDATED = 'inventory-level.updated',
  INVENTORY_LEVEL_DELETED = 'inventory-level.deleted',
  INVITE_CREATED = 'invite.created',
  NOTE_CREATED = 'note.created',
  NOTE_UPDATED = 'note.updated',
  NOTE_DELETED = 'note.deleted',
  ORDER_PLACED = 'order.placed',
  ORDER_UPDATED = 'order.updated',
  ORDER_CANCELED = 'order.canceled',
  ORDER_COMPLETED = 'order.completed',
  ORDER_ORDERS_CLAIMED = 'order.orders_claimed',
  ORDER_GIFT_CARD_CREATED = 'order.gift_card_created',
  ORDER_PAYMENT_CAPTURED = 'order.payment_captured',
  ORDER_PAYMENT_CAPTURE_FAILED = 'order.payment_capture_failed',
  ORDER_FULFILLMENT_CREATED = 'order.fulfillment_created',
  ORDER_SHIPMENT_CREATED = 'order.shipment_created',
  ORDER_FULFILLMENT_CANCELED = 'order.fulfillment_canceled',
  ORDER_RETURN_REQUESTED = 'order.return_requested',
  ORDER_ITEMS_RETURNED = 'order.items_returned',
  ORDER_RETURN_ACTION_REQUIRED = 'order.return_action_required',
  ORDER_REFUND_CREATED = 'order.refund_created',
  ORDER_REFUND_FAILED = 'order.refund_failed',
  ORDER_SWAP_CREATED = 'order.swap_created',
  ORDER_EDIT_CREATED = 'order-edit.created',
  ORDER_EDIT_UPDATED = 'order-edit.updated',
  ORDER_EDIT_CANCELED = 'order-edit.canceled',
  ORDER_EDIT_DECLINED = 'order-edit.declined',
  ORDER_EDIT_REQUESTED = 'order-edit.requested',
  ORDER_EDIT_CONFIRMED = 'order-edit.confirmed',
  ORDER_EDIT_ITEM_CHANGE_CREATED = 'order-edit-item-change.CREATED',
  ORDER_EDIT_ITEM_CHANGE_DELETED = 'order-edit-item-change.DELETED',
  PAYMENT_CREATED = 'payment.created',
  PAYMENT_UPDATED = 'payment.updated',
  PAYMENT_PAYMENT_CAPTURED = 'payment.payment_captured',
  PAYMENT_PAYMENT_CAPTURE_FAILED = 'payment.payment_capture_failed',
  PAYMENT_PAYMENT_REFUND_CREATED = 'payment.payment_refund_created',
  PAYMENT_PAYMENT_REFUND_FAILED = 'payment.payment_refund_failed',
  PAYMENT_COLLECTION_CREATED = 'payment-collection.created',
  PAYMENT_COLLECTION_UPDATED = 'payment-collection.updated',
  PAYMENT_COLLECTION_DELETED = 'payment-collection.deleted',
  PAYMENT_COLLECTION_PAYMENT_AUTHORIZED = 'payment-collection.payment_authorized',
  PRODUCT_CREATED = 'product.created',
  PRODUCT_UPDATED = 'product.updated',
  PRODUCT_DELETED = 'product.deleted',
  PRODUCT_CATEGORY_CREATED = 'product-category.created',
  PRODUCT_CATEGORY_UPDATED = 'product-category.updated',
  PRODUCT_CATEGORY_DELETED = 'product-category.deleted',
  PRODUCT_VARIANT_CREATED = 'product-variant.created',
  PRODUCT_VARIANT_UPDATED = 'product-variant.updated',
  PRODUCT_VARIANT_DELETED = 'product-variant.deleted',
  PUBLISHABLE_API_KEY_CREATED = 'publishable_api_key.created',
  PUBLISHABLE_API_KEY_REVOKED = 'publishable_api_key.revoked',
  REGION_CREATED = 'region.created',
  REGION_UPDATED = 'region.updated',
  REGION_DELETED = 'region.deleted',
  RESERVATION_ITEM_CREATED = 'reservation-item.created',
  RESERVATION_ITEM_UPDATED = 'reservation-item.updated',
  RESERVATION_ITEM_DELETED = 'reservation-item.deleted',
  SALES_CHANNEL_CREATED = 'sales_channel.created',
  SALES_CHANNEL_UPDATED = 'sales_channel.updated',
  SALES_CHANNEL_DELETED = 'sales_channel.deleted',
  STOCK_LOCATION_CREATED = 'stock-location.created',
  STOCK_LOCATION_UPDATED = 'stock-location.updated',
  STOCK_LOCATION_DELETED = 'stock-location.deleted',
  SWAP_CREATED = 'swap.created',
  SWAP_RECEIVED = 'swap.received',
  SWAP_FULFILLMENT_CREATED = 'swap.fulfillment_created',
  SWAP_SHIPMENT_CREATED = 'swap.shipment_created',
  SWAP_PAYMENT_COMPLETED = 'swap.payment_completed',
  SWAP_PAYMENT_CAPTURED = 'swap.payment_captured',
  SWAP_PAYMENT_CAPTURE_FAILED = 'swap.payment_capture_failed',
  SWAP_REFUND_PROCESSED = 'swap.refund_processed',
  SWAP_PROCESS_REFUND_FAILED = 'swap.process_refund_failed',
  ORDER_UPDATE_TOKEN_CREATED = 'order-update-token.created',
  USER_CREATED = 'user.created',
  USER_UPDATED = 'user.updated',
  USER_PASSWORD_RESET = 'user.password_reset',
  USER_DELETED = 'user.deleted',
}

export enum ETypeTemplateMail {
  NORMAL = 'normal',
  VIP = 'vip',
}

export enum EMailTemplateHtmlReplace {
  CONTENT = '{{ mail_content }}',
  HEADING = '{{ mail_heading }}',
  PREHEADER = '{{ mail_preheader }}',
}

export enum EMailAvailableVariables {
  GUEST_EMAIL = '{{ guest_email }}',
  USER_EMAIL = '{{ user_email }}',
  USER_FIRST_NAME = '{{ user_first_name }}',
  USER_LAST_NAME = '{{ user_last_name }}',
}

export enum EConditionSegment {
  CHECKOUT_BUT_DONT_BUY = 'checkout_but_dont_buy',
}

export enum ETimeTypeSegment {
  MANUAL = 'manual',
  MINUTE = 'minute',
  HOUR = 'hour',
  DAY = 'day',
  WEEK = 'week',
  MONTH = 'month',
}
